### ISSUE TITLE
Would you please provide the database file? Thank you very much indeed

### ISSUE THREAD

**Issue by livelychen** [MuellerMH/hotelbookingwebapp#2]
I looked at the source file and connected it to the local database. Would you please provide the database file? Thank you very much indeed

**Comment by MuellerMH** [comment]
Hi the database is in the project it's a MySQL workbench file .

Am 22.07.2017 18:21 schrieb "Chen" <notifications@github.com>:

I looked at the source file and connected it to the local database. Would
you please provide the database file? Thank you very much indeed

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MuellerMH/hotelbookingwebapp/issues/2>, or mute the
thread

**Comment by livelychen** [comment]
Wow, finally found it. Blame me for not paying attention
